### PR TITLE
Update for Python 3.

### PR DESCRIPTION
**Pull request by kdienes**
This patch updates xpybutil to be compatible with both Python 2 and 3.

Some notes:
- I converted xrange() to range(), and iteritems() to items(), without conditionalizing for Python 2/3.  It seemed that in all cases the data involved was small enough to not be worth adding extra complexity to handle the difference.
- I use encode('ascii') to encode atom names before sending for both Python 2 and 3.  I used ascii and not utf-8 so that it would generate an error if the string isn't ASCII.  I could have gone to more effort to avoid a string operation on Python 2, but didn't think it was worth it.

I'm happy to address either of these notes differently if you have a preference, but figured I'd throw out an initial patch as a suggestion to see what you think.  Thanks!

### CODE REVIEW

**Comment by BurntSushi** [comment]
This looks pretty great. I'm surprised that this was all that was necessary. Thank you!

@kdienes I'm not really using this library any more, so I doubt I make for a good maintainer. Would you like me to give you commit access to the repo?

**Comment by kdienes** [comment]
Thanks!  Yes; the xpybutil part of the changes were surprisingly straightforward.  The harder part was updating xpyb itself to use newer-style buffers/memory views.  I got enough of a start on that to make it work, but I'm confident that there are (at least) some memory leaks.  I suspect the right approach there is to rewrite the entire extension part in cython, but that's a bigger change and I want to check with the xpyb maintainers before I go much further.

I'd be happy to help maintain the library, though I don't claim to be an expert on it.  I'm using it pretty heavily these days though, so I expect that will change as I get more experience with it.

Do you have a sense of the major consumers of the library?  My biggest concern would be that I don't want to take/make changes I shouldn't out of ignorance of some of the use-cases.

**Comment by kdienes** [comment]
Thanks! Yes; the xpybutil part of the changes were surprisingly 
straightforward. The harder part was updating xpyb itself to use 
newer-style buffers/memory views. I got enough of a start on that to 
make it work, but I'm confident that there are (at least) some 
memory leaks. I suspect the right approach there is to rewrite the 
entire extension part in cython, but that's a bigger change and I 
want to check with the xpyb maintainers before I go much further.

I'd be happy to help maintain the library, though I don't claim to 
be an expert on it. I'm using it pretty heavily these days though, 
so I expect that will change as I get more experience with it.

Do you have a sense of the major consumers of the library? My 
biggest concern would be that I don't want to take/make changes I 
shouldn't out of ignorance of some of the use-cases.

**Comment by BurntSushi** [comment]
> I'd be happy to help maintain the library, though I don't claim to be an expert on it. I'm using it pretty heavily these days though, so I expect that will change as I get more experience with it.

That's a good enough reason for me. I made you a collaborator. :-)

> Do you have a sense of the major consumers of the library? My biggest concern would be that I don't want to take/make changes I shouldn't out of ignorance of some of the use-cases.

AFAIK, I *was* the biggest consumer when I tried to a [window manager in Python](https://github.com/BurntSushi/pyndow), but that project turned out to be a failure. (A few later, I wrote [a window manager in Go](https://github.com/BurntSushi/wingo).) Since then, there has been a very small trickle of interest, but I don't know of any major consumers.

I'm happy to consult with you on major changes, but as far as I'm concerned, you have carte blanche.

**Pull request merged**
