### PR TITLE
Add support for xcffib

### PR DESCRIPTION
**Pull request by felixonmars**
A simple wrapper called `compat.py` was introduced to help with the different naming of module and exceptions that this project used. I have tested with Deepin Screenshot and it works fine.

Please let me know if you see any improvement, thanks!

### CODE REVIEW

**Comment by felixonmars** [comment]
A friendly ping :)

I see this project may not be actively maintained now, but I still want to know if I can help in any way.

**Comment by BurntSushi** [comment]
@felixonmars Thanks for this PR. I guess my issue is that this repo has no tests, so there's no way to verify that everything actually works. I do actually still use this code in my day-to-day life that runs a pager I made years ago. So in order to merge this PR, I need to try your branch with my pager and make sure everything works. That might take me some time.

Indeed though, I don't really intend to improve this repo.

**Comment by felixonmars** [comment]
I see, thanks for the info.

**Comment by kdienes** [comment]
I've merged this, but seem to have done it in a way that confused Github.  I did some light testing and it all looks to be working.  Thanks for your contribution!

**Pull request closed without merging**
